/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxw_javacallc_Jni */

#ifndef _Included_com_lxw_javacallc_Jni
#define _Included_com_lxw_javacallc_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxw_javacallc_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lxw_javacallc_Jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lxw_javacallc_Jni
 * Method:    addString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxw_javacallc_Jni_addString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lxw_javacallc_Jni
 * Method:    increaeArrayElss
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lxw_javacallc_Jni_increaeArrayElss
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_lxw_javacallc_Jni
 * Method:    vetifyPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lxw_javacallc_Jni_vetifyPassword
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
